# Generated by Django 3.1.2 on 2020-12-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170917_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscribes',
            field=models.ManyToManyField(blank=True, related_name='subscribe', to='blog.Profile'),
        ),
    ]
