# Generated by Django 3.1.2 on 2020-12-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201218_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blog_name',
            field=models.CharField(default='my blog', max_length=1024, verbose_name='Название блога'),
        ),
    ]
