# Generated by Django 3.1.2 on 2020-12-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201219_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blog_name',
            field=models.CharField(max_length=1024, verbose_name='Название блога'),
        ),
    ]
