# Generated by Django 3.1.2 on 2020-12-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201219_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readedpost',
            name='readed',
            field=models.DateTimeField(auto_now=True, verbose_name='Прочитано'),
        ),
    ]
