# Generated by Django 3.1.4 on 2020-12-22 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0014_remove_profile_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ReadedPost',
        ),
    ]
